project:
  type: website
  resources:
    - lectures/14/14-decision-errors.pdf

website:
  page-navigation: true
  title: "STA 101 Fall 2024"
  description: "Homepage for STA 101 Data Analysis and Statistical Inference at Duke University, Fall 2024."
  site-url: "https://sta101-f24.github.io"

#  repo-url: https://github.com/sta101-f24/sta101-f24.github.io
#  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#9c1625"
    logo: "images/logo.png"
    pinned: true
    align: center

#    tools:
#      - icon: person-fill
#        text: "Canvas"
#        menu:
#          - text: Announcements
#            url: https://canvas.duke.edu/courses/4625/announcements
#          - text: Grades
#            url: https://canvas.duke.edu/courses/4625/gradebook
#          - text: Tutorial submission
#            url: https://canvas.duke.edu/courses/4625/quizzes

    style: docked
    search: true
    collapse-level: 1

    contents:
      - section: "Syllabus"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-team.qmd
            text: Teaching team
          - href: course-materials.qmd
            text: Course materials
          - href: course-grading.qmd
            text: Assignments and grading
          - href: course-policies.qmd
            text: Course policies
          - href: course-resources.qmd
            text: University resources
          - href: index.qmd
            text: Schedule
            
      - section: "Labs"
        contents:
          - href: labs/lab-1.qmd
            text: Lab 1
#      - href: project/project-2.qmd
#        text: Project
      - section: "Computing primers"
        contents:
          - href: computing/computing-access.qmd
            text: Accessing RStudio
          - href: computing/computing-moving.qmd
            text: Moving files around
          - href: computing/computing-histogram.qmd
            text: Histogram basics
          - href: computing/computing-cheatsheets.qmd
            text: Cheatsheets

  page-footer:
    right: "This page is built with 🤍 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Mine Çetinkaya-Rundel and John Zito"
    background: "#9c1625"


format:
  html:
    theme:
      light: [cosmo, style/sta101.scss]
#      dark: [cosmo, style/sta101.scss, style/dark.scss]
    linkcolor: "#798b93"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto

editor: visual
