---
title: "Policies"
---

Duke Community standard

## Collaboration

-   You are encouraged to discuss and help one another with the labs, but you should not share solutions (e.g. emailing a friend your code). All submitted work must be your own;
-   You are forbidden from collaborating in any way on the exams;
-   You are enthusiastically encouraged to collaborate with your teammates on all aspects of the final project.

## Communication

If you wish to ask content-related questions in writing, please do not do so via e-mail. Instead, please use the course discussion forum [Ed Discussion](https://edstem.org/us/courses/64268/discussion/). That way all members of the teaching team can see your question, and all students can benefit from the ensuing discussion. You are also encouraged to answer one another's questions.

If you have questions about personal matters that may not be appropriate for the public course forum (e.g. illness, accommodations, etc), then please e-mail the instructor directly (`john.zito@duke.edu`).

## Use of online resources, including AI

You may make use of any online resources (e.g. `StackOverflow`) but you must explicitly cite where you obtained any code you directly use (or use as inspiration). Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

You should treat generative AI, such as ChatGPT, like other online resources. Two guiding principles govern how to use AI in this course:

    1.  *Cognitive dimension:* Working with AI should not reduce your thinking ability.
        We will practice using AI to facilitate—rather than hinder—learning.

    2.  *Ethical dimension***:** Students using AI should be transparent about their use and ensure it aligns with academic integrity.

    -   {{< fa check >}} **AI tools for code:** You may use the technology for coding examples on assignments; if you do so, you must explicitly cite where you obtained the code.
        Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.
        You may use [these guidelines](https://guides.lib.monash.edu/c.php?g=219786&p=6972087) to cite AI-generated content.
        The bare minimum citation must include the AI tool you're using (e.g., ChatGPT) and your prompt.
        The prompt you use cannot be copied and pasted directly from the assignment; you must create a prompt yourself.

    -   {{< fa ban >}} **AI tools for narrative:** Unless instructed otherwise, you may not use generative AI to generate a narrative that you then copy-paste verbatim into an assignment or edit and then insert into your assignment.

    -   {{< fa check >}} **AI tools for learning:** You're welcomed to ask AI tools questions that might help your learning and understanding in this course.

    In general, you may use generative AI as a resource as you complete assignments but not to answer the exercises for you.
    You are ultimately responsible for the work you turn in; it should reflect *your* understanding of the course content.
    Identifying AI-generated content is fairly straightforward.
    Any code identified as AI-generated but not cited as such and any narrative identified as AI-generated will be considered plagiarism and treated as such.

## Late work and extensions

No late work will be accepted unless you request an extension in advanced. All reasonable requests will be entertained, but extensions will not be long.

## Regrade requests

You have one week after receiving a grade to dispute it. Regrade requests can be made in Gradescope, and the instructor will do the regrading.

## Artificial intelligence
