---
title: "Assignments and grading"
---

The final course grade will be calculated as follows:

| Category      | Percentage |
|---------------|------------|
| Labs          | 25%        |
| Exam 1        | 25%        |
| Exam 2        | 25%        |
| Final project | 25%        |

The final letter grade will be determined based on the following thresholds, **which will not change**:

| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |

## Labs

In labs, you will apply the concepts discussed in lecture to various data analysis scenarios. Labs will focus on both computation and conceptualization. Lab assignments will be completed using Quarto and submitted as as a PDF for grading in Gradescope.

## Exams

There will be two exams. Each exam will be comprised of two components:

-   In class: 75 minute in-class exam. This exam is closed book, however you are allowed to use one sheet of notes ("cheat sheet") to the midterm and the final. This sheet must be no larger than 8 1/2 x 11, and **must be prepared by you**. You may use both sides of the sheet. (70% of the grade)

-   Take home: Following the in class exam, you'll have 48 hours to complete the take home portion of your exam. The take home portion will follow from the in class exam and focus on the analysis of a dataset introduced in the take home exam. (30% of the grade)

Through these exams you have the opportunity to demonstrate what you've learned in the course thus far. Each exam will include small analyses and computational tasks related to the content in application exercises and labs. More details about the content and structure of the exams will be discussed during the semester.

See the [course schedule](https://sta101-f24.github.io/) for dates and times of the exams. Exam dates cannot be changed and no make-up exams will be given. If you can't take the exams on these dates, you should drop this class.

## Final project

The course ends with a final project where you will explore a question and data set of your own. More details about the projects will be provided during the semester. The project will be completed in teams. All team members are expected to contribute equally to the completion of each project and you will be asked to evaluate your team members. Failure to adequately contribute to an assignment will result in a penalty to your mark relative to the team's overall mark.

See the [course schedule](https://sta101-f24.github.io/) for dates and times of project deadlines. Project deadlines cannot be changed. If you cannot be in class for the final project presentation (which takes place during our final exam period), you should drop this class.
