---
title: "Course overview"
---

## Course description

Introduction to statistics as a science of understanding and analyzing data. Themes include data collection, exploratory analysis, inference, and modeling. Focus on principles underlying quantitative research in social sciences, humanities, and public policy. Research projects teach the process of scientific discovery and synthesis and critical evaluation of research and statistical arguments. Readings give perspective on why in 1950, S. Wilks said, 'Statistical thinking will one day be as necessary a qualification for efficient citizenship as the ability to read and write.'

**Prerequisites:** none.

## Class meetings

| Meeting  | Location                       | Time                         | Staff            |
|------------------|-------------------|------------------|------------------|
| Lectures | Social Sciences 139            | Tue, Thu 03:05 PM - 04:20 PM | John Z           |
| Lab 1    | Perkins LINK 087 (Classroom 3) | Fri 10:05 AM - 11:20 AM      | John G, Camilla  |
| Lab 2    | Perkins LINK 087 (Classroom 3) | Fri 11:45 AM - 01:00 PM      | Katie, Meghna    |
| Lab 3    | Perkins LINK 087 (Classroom 3) | Fri 01:25 PM - 02:40 PM      | Leah, Nichole    |
| Lab 4    | Perkins LINK 087 (Classroom 3) | Fri 08:30 AM - 09:45 AM      | Benjamin, Sayali |

::: callout-warning
For reasons unknown to rational people, the labs are not exactly numbered in chronological order. "Lab 4" is in fact the first one of the day.
:::
