{
  "hash": "2d55a7e4cbefa4bd0ffaa78fd1e4b20e",
  "result": {
    "engine": "knitr",
    "markdown": "---\n  title: \"The normal distribution\"\n---\n\n\nThe **normal distribution** is the familiar bell curve. The central limit theorem says that the sampling distribution of a statistic (sample mean, proportion, difference, etc) looks more and more like a normal distribution the more data we have. This gives us permission to use a normal distribution to approximate the sampling distribution, and use the convenient properties of the bell curve to compute confidence intervals and hypothesis tests.\n\nThis primer introduces you to the basic commands for working with the normal distribution.\n\n## Load packages\n\nThe `openintro` package has tools for working with the normal distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) \nlibrary(openintro)\n```\n:::\n\n\n## Example: bone density\n\nSuppose the bone density of 65-year-old women is normally distributed with mean 809 $mg/cm^3$ and standard deviation of 140 $mg/cm^3$. For reference, here are the densities for three types of wood:\n\n-   Plywood: 540 $mg/cm^3$\n\n-   Pine: 600 $mg/cm^3$\n\n-   Mahogany: 710 $mg/cm^3$\n\nIf $X$ represents the bone density of 65-year-old women, then we can summarize the situation mathematically by writing:\n\n$$\nX \\sim N(\\mu = 809, \\sigma = 140).\n$$\n\nLet's give all of the numbers above names and store them in the computer for later:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbone_density_mean <- 809\nbone_density_sd <- 140\n\nplywood <- 540\npine <- 600\nmahogany <- 710\n```\n:::\n\n\n## Plot the bell curve\n\nThis handy-dandy function plots a bell curve:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnormTail(m = 0, s = 1)\n```\n\n::: {.cell-output-display}\n![](computing-normal_files/figure-html/plot-bell-1.png){width=672}\n:::\n:::\n\n\nYou can add several arguments to customize:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnormTail(m = bone_density_mean, \n         s = bone_density_sd, \n         main = \"Distribution of bone density of 65-year-old women\",\n         xlab = \"mg/cm^3\",\n         xlim = c(200, 1400))\n```\n\n::: {.cell-output-display}\n![](computing-normal_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## Compute quantiles under the normal distribution\n\nThe `qnorm` function computes the quantiles of a normal distribution. If we wanted the 50% quantile (AKA the median), we would say\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.5, mean = 0, sd = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nIn this case we just get back the mean, because the normal distribution is perfectly symmetric, and mean and median are equal for symmetric distributions.\n\nIf we wanted the inner quartile range (IQR) for a normal distribution, here it goes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq25 <- qnorm(0.25, mean = 0, sd = 1)\nq75 <- qnorm(0.75, mean = 0, sd = 1)\n\nIQR <- q75 - q25\nIQR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.34898\n```\n\n\n:::\n:::\n\n\n## Compute and visualize probabilities under the normal distribution\n\nWhat is the probability that a randomly selected 65-year-old woman has bones that are as or less dense than pine? If we add an `L` argument (for \"lower\") to `normTail`, we can visualize the answer:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnormTail(m = bone_density_mean, s = bone_density_sd, L = pine,\n         main = \"Distribution of bone density of 65-year-old women\",\n         xlab = \"mg/cm^3\",)\n```\n\n::: {.cell-output-display}\n![](computing-normal_files/figure-html/shade-lower-tail-1.png){width=672}\n:::\n:::\n\n\nNotice how this may come in handy when we have to compute something like a $p$-value. In order to compute the probability (area) under the bell curve of being less than 600 $mg/cm^3$, we can use the `pnorm` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(pine, mean = bone_density_mean, sd = bone_density_sd, lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06773729\n```\n\n\n:::\n:::\n\nAbove, we asked about being *under* 600 in the distribution. But we could just have easily looked at being *over* 600 by adding a `U` argument (for \"upper\"):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnormTail(m = bone_density_mean, s = bone_density_sd, U = pine,\n         main = \"Distribution of bone density of 65-year-old women\",\n         xlab = \"mg/cm^3\",)\n```\n\n::: {.cell-output-display}\n![](computing-normal_files/figure-html/shade-upper-tail-1.png){width=672}\n:::\n:::\n\n\nTo get the number, we change the `lower.tail` argument:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(pine, mean = bone_density_mean, sd = bone_density_sd, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9322627\n```\n\n\n:::\n:::\n\n\nNotice that the probability of being at or below 600 is 6.77%. The probability of being above 600 is 93.23% That covers everything, so taken together you get 100%, which is the total area under the bell curve.",
    "supporting": [
      "computing-normal_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}