{
  "hash": "2f535020dd09726ee54d491029ece9a5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Worked example: estimating a single proportion\"\nfig-width: 6\nfig-asp: 0.618\n---\n\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\n```\n:::\n\n\n## Data\n\nIn a [survey conducted by Survey USA](https://www.surveyusa.com/client/PollReport.aspx?g=4d09191d-b0b5-42cd-91c8-bd1bdf587199) between September 30, 2023 and October 3, 2023, 2759 registered voters from all 50 US states were asked\n\n> America will hold an election for President of the United States next November. Not everyone makes the time to vote in every election. Which best describes you? Are you certain to vote? Will you probably vote? Are the chances you will vote about 50/50? Or will you probably not vote?\n\nThe data from this survey can be found in `voting-survey.csv`.\n\n## Task 1\n\nDo three things:\n\n-   load the data;\n-   visualize the distribution of survey responses;\n-   calculate the proportion of respondents who are certain to vote in the next presidential election.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Part 1\n\nvoting_survey <- read_csv(\"data/voting-survey.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 2759 Columns: 2\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): vote\ndbl (1): id\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Part 2\n\nggplot(voting_survey, aes(y = vote)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](ae-12-voters_files/figure-html/vote-bars-1.png){width=576}\n:::\n\n```{.r .cell-code}\n# Part 3\n\nvoting_survey |>\n  count(vote) |>\n  mutate(props = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  vote                       n  props\n  <chr>                  <int>  <dbl>\n1 About 50/50 chance       293 0.106 \n2 Certain to vote         1921 0.696 \n3 Not sure                  44 0.0159\n4 Probably will not vote    92 0.0333\n5 Will probably vote       409 0.148 \n```\n\n\n:::\n:::\n\n\n## Task 2\n\nBased on these data, we want to estimate the true proportion of registered US voters who are certain to vote in the next presidential election. Use the bootstrap to approximate a 95% confidence interval for this quantity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare the data for analysis (pre-processing)\n\nvoting_survey <- voting_survey |>\n  mutate(vote = if_else(\n                        vote == \"Certain to vote\",\n                        \"Certain to vote\",\n                        \"Not certain to vote\")\n         )\n\nset.seed(20)\n\nboot_dist <- voting_survey |>\n  specify(response = vote, success = \"Certain to vote\") |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"prop\")\n\nci <- boot_dist |>\n  get_ci()\nci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1    0.679    0.714\n```\n\n\n:::\n\n```{.r .cell-code}\nvisualize(boot_dist) + \n  shade_ci(ci)\n```\n\n::: {.cell-output-display}\n![](ae-12-voters_files/figure-html/bootstrap-ci-1.png){width=576}\n:::\n:::\n\n\n## Task 3\n\nBAD: \"There is a 95% probability that the true proportion is between 67.9% and 71.4%.\"\n\nNOT SO BAD: \"95% of the time, the true proportion is between 67.9% and 71.4%.\"\n\nCORRECT, BUT SHADY: \"We are 95% confident that the true proportion is between 67.9% and 71.4%.\"\n\nCorrect: \"95% of the time, an interval constructed like this one will contain the true proportion.\"\n\n## Task 4\n\nPew says that 66% of eligible US voters turned out for the 2020 presidential election. A newspaper claims that even more people will turnout in 2024, and cites this survey as evidence. Do these data provide convincing evidence for this claim?\n\nDo two things:\n\n\\- state the hypotheses\n\np = proportion of voters that turn out in 2024\n\nH_0: p = 0.66\n\nH_1: p \\> 0.66\n\nOne-sided test\n\n\\- conduct a randomization test, at 5% discernability level. What is the conclusion of the test?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_stat <- voting_survey |>\n    specify(response = vote, success = \"Certain to vote\") |>\n    calculate(stat = \"prop\")\n\nset.seed(525600)\n\nnull_dist <- voting_survey |>\n  specify(response = vote, success = \"Certain to vote\") |>\n  hypothesize(null = \"point\", p = 0.66) |>\n  generate(reps = 1000, type = \"draw\") |>\n  calculate(stat = \"prop\")\n\nnull_dist |>\n  get_p_value(obs_stat, direction = \"greater\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Please be cautious in reporting a p-value of 0. This result is an approximation\nbased on the number of `reps` chosen in the `generate()` step.\nℹ See `get_p_value()` (`?infer::get_p_value()`) for more information.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1       0\n```\n\n\n:::\n:::\n\n\n## Task 5\n\n\"There is a 0% chance that the null is true.\"\n\n\"If the null were true, there is a 0% chance of seeing data like what we saw.\"\n",
    "supporting": [
      "ae-12-voters_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}